### ISSUE TITLE
@unoverlays/vue 0.6.0 ts中提示没有only参数

### ISSUE THREAD

**Issue by tetap** [hairyf/overlays#11]
![image](https://user-images.githubusercontent.com/57606461/229438034-9e801f46-e06a-4d15-bd56-a8bc35db551f.png)

**Comment by hairyf** [comment]
你好，请你清除缓存在尝试，或提供更详细的上下文，以下是我的推测

- 你使用了 renderOverlay，renderOverlay 不支持使用 only 属性
- 安装过后重新打开编辑器，并使用 defineOverlay 定义弹出层
