### ISSUE TITLE
如何支持 element-plus 全局配置组件

### ISSUE THREAD

**Issue by 153264** [hairyf/overlays#39]
# 在主应用配置，但是弹出层的app应用没有配置
APP应用也在入口`main.ts` use unoverlay了
![1684240791266](https://github.com/hairyf/overlays/assets/36463512/e79a5a75-e7e0-4aae-b3cd-8234d3b71403)
![1684240934478](https://github.com/hairyf/overlays/assets/36463512/3b087e2d-4cc3-474b-a892-49f47db6620a)
![1684240934498](https://github.com/hairyf/overlays/assets/36463512/ceb01723-62d5-4d14-8ec8-2f1c62bc137a)

**Comment by hairyf** [comment]
由于 `element-plus` 是使用组件来进行挂载注入更多应用信息，而 `@overlays/vue` 只能继承当前 `createApp` 中的全局属性，所以你需要在 `UnifiedOverlay` 组件中使用 `el-config-provider`

```html
<!-- overlay.vue -->
<script setup>
const { visible, resolve, reject } = useOverlay({/* ... */})
</script>

<template>
  <el-config-provider>
     <el-dialog>...</el-dialog>
   </el-config-provider>
</template>
```

目前你可以将 `el-config-provider` 封装成一个通用的注入层，并提供给 `App.vue` 和 `overlays` 组件使用。

```html
<!-- mount-privder.vue -->
<template>
  <el-config-provider ...>
     <slot />
   </el-config-provider>
</template>
```

**Comment by 153264** [comment]
你的意思是这样吗？
```vue
<!-- mount-privder.vue -->
<template>
  <el-config-provider ...>
     <slot />
   </el-config-provider>
</template>
<!-- App.vue -->
<template>
  <mount-privder>
    <!-- code ... -->
  </mount-privder>
</template>
<!-- overlays.vue 弹出层组件 -->
<template>
  <mount-privder>
     <el-dialog>
      <!-- code... -->
     </el-dialog>
  </mount-privder>
</template>
```

**Comment by hairyf** [comment]
> 你的意思是这样吗？
> 
> ```
> 
> <template>
>   <el-config-provider ...>
>      <slot />
>    </el-config-provider>
> </template>
> 
> <template>
>   <mount-privder>
>     
>   </mount-privder>
> </template>
> 
> <template>
>   <mount-privder>
>      <el-dialog>
>       
>      </el-dialog>
>   </mount-privder>
> </template>
> ```

没错，是这么处理

**Comment by hairyf** [comment]
是的，你也可以使用 [useInjectHolder](https://unoverlays.vercel.app/zh/vue/advanced/holder.html) API，通过创建持有者，塞入到当前的 vnode 当中，它可以在注入层组件内继承属性。

**Comment by 153264** [comment]
这种不太适合我，我是使用`createOverlay`统一导出js，页面调用弹出。
