### ISSUE TITLE
useOverlay函数未捕获meta.deferred拒绝状态，导致每次调用reject时浏览器都会抛出异常

### ISSUE THREAD

**Issue by Curtion** [hairyf/overlays#48]
[代码位置](https://github.com/hairyf/overlays/blob/2e7ea83807082e88dca3c3a09db3dbb759e9ab77/packages/%40react/src/composable/useOverlay.ts#LL78C43-L78C43)

调用reject后，等延时结束时浏览器会抛出异常，且该异常似乎在业务端无法进行捕获?

![image](https://github.com/hairyf/overlays/assets/14846890/e86a2a57-5035-4ea0-a48d-802cf771d429)
![image](https://github.com/hairyf/overlays/assets/14846890/dafd77ba-c20d-49bb-96d6-3844b6008287)

`meta.deferred?.catch(() => {}).finally...`  是否可行?

**Comment by hairyf** [comment]
使用 finally 未捕获错误，所以应该是 finally().catch，现在它已经被修复
