### ISSUE TITLE
[求助] git仓库拉取后如何开发调试

### ISSUE THREAD

**Issue by 153264** [hairyf/overlays#59]
1. 拉取仓库执行 `pnpm install` 
2. playgrounds\vue 执行 `pnpm install`
3. 根目录执行 `pnpm play:vue`

![image](https://github.com/hairyf/overlays/assets/36463512/f6660f17-8306-458c-9986-4d5320af2816)

**Comment by hairyf** [comment]
缺少 @overlays/vue 应该在 playgrounds/vue 中安装，可能是我不小心删了，所以只需要在这个目录下安装就可以了

**Comment by 153264** [comment]
playgrounds/vue 我看 package.json 是使用了 workspace:^ 引用
 
![image](https://github.com/hairyf/overlays/assets/36463512/838a4776-44eb-410b-99a0-c34d820665e9)

我目前的临时解决方法是直接把  playgrounds/vue 复制到 packages 里面运行，就正常了
