### ISSUE TITLE
devtools如何调试这个组件

### ISSUE THREAD

**Issue by gjfei** [hairyf/overlays#6]
没有和父级组件联系起来

**Comment by hairyf** [comment]
js / ts 弹出类模态框区别于应用上下文，无法通过应用上下文进行查看

我认为可以通过 createVNode 更改为 createApp 来解决，这会在 devtools 中显示一个 overlay 应用

这在 [quasar/createChildApp](https://github.com/quasarframework/quasar/blob/dev/ui/src/install-quasar.js#L26) 中有实际案例

实际上还有一种办法 #1 ，不过实际会很繁琐所以没有考虑，这在 react 应用中经常出现

**Comment by hairyf** [comment]
在   [v0.3.3](https://github.com/TuiMao233/unoverlays/releases/tag/v0.3.3) 中解决
