### ISSUE TITLE
vue3中OverlaysProvider + useOverlay使用异常

### ISSUE THREAD

**Issue by andyyxw** [hairyf/overlays#76]
![image](https://github.com/hairyf/overlastic/assets/41931722/32204109-4bf0-4c7c-886e-4bf5bda46a99)
`useOverlay`使用时类型报错：
![image](https://github.com/hairyf/overlastic/assets/41931722/19036463-4c8b-4840-afb6-0c94559166ef)
![image](https://github.com/hairyf/overlastic/assets/41931722/145f89c9-5048-482a-a317-b600925e835d)
弹窗组件中接收到的`visible`为undefined，`props`接收正常
![image](https://github.com/hairyf/overlastic/assets/41931722/5736c41d-6cd1-487a-999d-ea616cbff3ae)
![image](https://github.com/hairyf/overlastic/assets/41931722/ced4f43d-1573-4be6-b43d-e8d10bd5d6af)

`defineOverlay`方式用着是ok的，但是没法拿到主题等全局信息，不得已用了provider。
文档中vue部分也没有`OverlaysProvider`+`useOverlay`使用教程，我是参照`react`部分的，请问是provider功能还没做好吗？

**Comment by hairyf** [comment]
目前暂时仅支持 react，vue 还没有测试，且该 api 后续可能有变化，建议暂时用 holder 模式
