### ISSUE TITLE
使用这个上下文会丢失

### ISSUE THREAD

**Issue by duopu** [hairyf/overlays#78]
我在子组件里面使用 i18n这个库
![image](https://github.com/hairyf/overlastic/assets/148187698/fcb23ee9-bbe0-4904-9937-2f2c1462af6d)
![image](https://github.com/hairyf/overlastic/assets/148187698/cca2d561-ac20-4586-a07a-75504f299565)

**Comment by hairyf** [comment]
使用 useInjectHolder 或者重新注入一遍

**Comment by hairyf** [comment]
新版本已新增 OverlayProvider / useOverlay
