### ISSUE TITLE
vue3使用@overlastic/vue 0.8.0会白屏

### ISSUE THREAD

**Issue by tetap** [hairyf/overlays#82]
![image](https://github.com/user-attachments/assets/6f6953fc-2f78-4d36-aedd-de81337222c9)
![image](https://github.com/user-attachments/assets/0944a26d-a8eb-428b-abd1-50cbececbf04)
![image](https://github.com/user-attachments/assets/2036dbd6-d9f0-4e44-a893-ffde22a441f2)

每当我c触发renderOverlay我的其他组件dom就会消失，当弹窗关闭时，body也被移除了。
![image](https://github.com/user-attachments/assets/6bf4974b-9529-440c-bf0b-39b5584117c9)

**Comment by tetap** [comment]
![image](https://github.com/user-attachments/assets/42c2c079-4421-4a7a-86d3-939a1f02bd05)

**Comment by tetap** [comment]
![image](https://github.com/user-attachments/assets/ab77b788-9d6f-4ea9-bb3d-e7decef4e262)

看样子就是这个container的问题。我改为重新新建一个div而不是body 解决了我的问题

**Comment by tetap** [comment]
![image](https://github.com/user-attachments/assets/b4952ab2-fd34-48de-b636-b7855b61d9a2)

这是我的最终解决方案，目前只测试vue3，具体这种写法的问题是否是为了兼容其他框架，因为这是core包.

**Comment by hairyf** [comment]
好的，不过下次合并请使用英文描述

**Comment by tetap** [comment]
> 好的，不过下次合并请使用英文描述

我的。我看很多人提issues都是中文描述 习惯性就提中文了。下次有合并遵循一下，谢谢
