### ISSUE TITLE
Can not use in vue 2 project

### ISSUE THREAD

**Issue by kikyous** [hairyf/overlays#9]
export 'Teleport' (imported as 'Teleport') was not found in 'vue-demi'

**Comment by kikyous** [comment]
I'm confused about use `@unoverlays/vue` or `@unoverlays/vue-v2`?

**Comment by kikyous** [comment]
In @unoverlays/vue-v2 package, there is not a named export `useOverlayMeta`.

**Comment by hairyf** [comment]
Hello, vue2 has not been disclosed yet

Yes, vue2 projects cannot use the useOverlayMeta method, but instead use the mixinOverlayMeta method

```ts
import { mixinOverlayMeta } from "@unoverlays/vue-v2"
export default {
   mixins: [ mixinOverlayMeta({ animation: 1000 }) ],
   methods: {
     onClick() {
        // use this.$visible
        // use this.$confirm or this.$cancel
     }
   }
}
```
> Please note that vue-v2 is in the experimental phase and the API may change at any time
I hope this will help you

I am still preparing and thinking about APIs and documentation for vue2, and I hope they can be helpful for some older projects.

**Comment by hairyf** [comment]
https://unoverlays.vercel.app/en/guide/support-vue2.html
